### ISSUE TITLE
Don't keep it up

### ISSUE THREAD

**Issue by tucnak** [alioygur/godash#1]
Stop programming man, it's not your jam.

**Comment by aliuygur** [comment]
why dear?

**Comment by tucnak** [comment]
overusing regular expressions and unidiomatic stuff, reddit squad nailed it

**Comment by sethgrid** [comment]
@tucnak assuming you are interested in Go code and the Go community (you have Go repos and you commented on someone else's repo), you should reconsider your approach to dealing with people who are not yet writing idiomatic Go. Instead, you could add value to both alioygur and the community in general by providing constructive feedback and linking to proper examples. It would be easy to say to you, "Stop communicating with others, it's not your jam." However, it is non-constructive and mean.

@alioygur you are getting some flak for having unidiomatic code. Lots of regexes, lots of interfaces, improper use of variable names (`isrune` vs `isRune`) and misuse of names (`IsNull(s string)` does not return if the string is Nil/Null - it checks if the string is empty). If you are interested in improving your Go, take time to read through the standard library and get a feel for what idiomatic code looks like. Make sure you've read things like Effective Go and other official blog posts. Unlike what @tucnak would suggest, you seem like a decent coder, but you may be trying to shoe-horn another language's patterns into Go, and that should usually be avoided.

Cheers.

**Comment by tucnak** [comment]
Cheers mate.
