### ISSUE TITLE
Don't validate emails with regex

### ISSUE THREAD

**Issue by sethgrid** [alioygur/godash#2]
Check out:
http://play.golang.org/p/fKwLaT3gY4

It shows many valid email addresses as invalid. See 

https://en.wikipedia.org/wiki/Email_address#Valid_email_addresses
https://davidcel.is/posts/stop-validating-email-addresses-with-regex/
Related:
http://stackoverflow.com/questions/201323/using-a-regular-expression-to-validate-an-email-address

If you _really_ want to use regular expressions (which is not Go's strong suit), just check if there is something before and after an `@`.

**Comment by aliuygur** [comment]
Thank you. I will refactor.

**Comment by aliuygur** [comment]
fixed d428c94c5ef5ab550f5184a7886d75b46e039700
